import{test}from'node:test';import assert from'node:assert/strict';import{DatabaseSync}from'node:sqlite';import fs from'node:fs';import{Database}from'../server/native/database';import{createCompany}from'../server/native/company';import{publicApi}from'../server/native/public';import{ownerEligible}from'../server/native/owner';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync('scripts/native/schema.sql','utf8'));db.exec(fs.readFileSync('scripts/native/bootstrap.sql','utf8'));db.exec("CREATE TABLE users(id TEXT,email TEXT,email_verified INTEGER);INSERT INTO users VALUES('u1','owner@example.com',1)");const sql={async sql(q:string,args:any[]=[]){return{rows:db.prepare(q).all(...args)}},async batch(ops:any[]){db.exec('BEGIN');try{const results=ops.map(o=>({rows:db.prepare(o.sql).all(...(o.args||[]))}));db.exec('COMMIT');return{results}}catch(e){db.exec('ROLLBACK');throw e}}};const ctx={sql,identity:{userId:'u1',email:'owner@example.com',master:true,companyId:undefined as string|undefined}};return{db,sql,ctx}}
async function seed(){const f=fixture();const a=await createCompany(f.ctx,{name:'Imobiliária A',ownerEmail:'owner@example.com'},true),b=await createCompany(f.ctx,{name:'Imobiliária B',ownerEmail:'other@example.com'},true);const user=new Database(f.sql,{userId:'u1',email:'owner@example.com',master:false,role:'owner',companyId:a.id});f.db.prepare("INSERT INTO property(id,company_id,title,price,type,\"transaction\",owner_name,owner_phone,owner_email) VALUES(?,?,'Residência',100000,'casa','venda','Segredo','99999999999','secret@example.com')").run('pa',a.id);f.db.prepare("INSERT INTO property(id,company_id,title,price,type,\"transaction\") VALUES(?,?,'Imóvel B',200000,'casa','venda')").run('pb',b.id);f.db.prepare("INSERT INTO lead(id,company_id,name,phone)VALUES('la',?,'Lead A','11999999999'),('lb',?,'Lead B','11988888888')").run(a.id,b.id);return{...f,a,b,user}}
test('tenant e Master selecionado ficam restritos à imobiliária escolhida',async()=>{const f=await seed();for(const db of [f.user,new Database(f.sql,{...f.ctx.identity,companyId:f.a.id})]){const r=await db.from('property').select('*');assert.equal(r.data.length,1);assert.equal(r.data[0].id,'pa');assert.equal((await db.from('property').update({title:'Invadido'}).eq('id','pb')).count,0)}});
test('anônimo não lê tabelas de negócio e Master sem seleção não mistura dados',async()=>{const f=await seed();for(const who of [{userId:'',master:false},f.ctx.identity])assert.ok((await new Database(f.sql,who).from('lead').select('*')).error)});
test('ligações de imóvel lead corretor são verificadas por imobiliária',async()=>{const f=await seed();assert.ok((await f.user.from('proposal').insert({property_id:'pb',lead_id:'la',value:100})).error);assert.ok((await f.user.from('visit').insert({property_id:'pa',lead_id:'lb',scheduled_at:new Date().toISOString()})).error);assert.ok((await f.user.from('lead').update({interest_property_id:'pb'}).eq('id','la')).error)});
test('corretor não altera financeiro equipe ou status da imobiliária',async()=>{const f=await seed();const u=new Database(f.sql,{userId:'r',master:false,role:'corretor',companyId:f.a.id});assert.ok((await u.from('commission').select('*')).error);assert.ok((await u.from('revenue').insert({description:'X',amount:10,date:'2026-09-17'})).error);assert.ok((await u.from('company_user').insert({email:'other@example.com'})).error);assert.ok((await u.from('company').update({status:'active'}).eq('id',f.a.id)).error)});
test('owner não altera cobrança nem promove perfil global ou vínculo arbitrário',async()=>{const f=await seed();assert.ok((await f.user.from('company').update({plano:'enterprise'}).eq('id',f.a.id)).error);assert.ok((await f.user.from('user_roles').insert({user_id:'u1',role:'super_admin'})).error);assert.ok((await f.user.from('company_user').insert({email:'x@example.com',user_id:'u1'})).error);assert.ok((await f.user.from('company_user').insert({email:'x@example.com',role:'owner'})).error)});
test('publicação filtra informações privadas de proprietário e imobiliária',async()=>{const f=await seed();const r=await publicApi(f.ctx,{action:'catalog',slug:f.a.slug});assert.equal(r.company.owner_email,undefined);assert.equal(r.properties[0].owner_name,undefined);assert.equal(r.properties[0].owner_phone,undefined);assert.equal(r.properties[0].owner_email,undefined);assert.equal(r.properties.length,1);await assert.rejects(()=>publicApi(f.ctx,{action:'catalog',slug:f.a.slug,id:'pb'}),/não encontrado/)});
test('reserva cria lead e visita atomicamente e duplicação não deixa lead órfão',async()=>{const f=await seed();const when=new Date(Date.now()+7*86400000);when.setUTCHours(12,0,0,0);const input={action:'book',slug:f.a.slug,id:'pa',scheduled_at:when.toISOString(),name:'Visita Teste',phone:'11977777777'};const r=await publicApi(f.ctx,input);assert.ok(r.protocolo);const n=f.db.prepare('SELECT COUNT(*) n FROM lead').get()?.n;await assert.rejects(()=>publicApi(f.ctx,input),/reservado/);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM lead').get()?.n,n);const slots=await publicApi(f.ctx,{action:'slots',slug:f.a.slug,id:'pa',date:when.toISOString().slice(0,10)});assert.deepEqual(slots.taken,[when.toISOString()])});
test('vitrine suspensa não publica imóveis e reserva inválida não grava lead',async()=>{const f=await seed();await assert.rejects(()=>publicApi(f.ctx,{action:'book',slug:f.a.slug,id:'pa',scheduled_at:'2000-01-01',name:'Teste',phone:'11977777777'}),/Horário/);f.db.prepare("UPDATE company SET status='blocked' WHERE id=?").run(f.a.id);await assert.rejects(()=>publicApi(f.ctx,{action:'catalog',slug:f.a.slug}),/não encontrada/)});
test('repetir status proposta não inventa receita ou duplica comissão',async()=>{const f=await seed();const r=await f.user.from('proposal').insert({property_id:'pa',lead_id:'la',value:100000}).single();assert.equal(r.error,null);for(let i=0;i<2;i++)assert.equal((await f.user.from('proposal').update({status:'aceita'}).eq('id',r.data.id)).error,null);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM revenue').get()?.n,0);assert.ok((await f.user.from('proposal').update({value:1}).eq('id',r.data.id)).error);const broker=f.db.prepare('SELECT id FROM company_user WHERE company_id=?').get(f.a.id) as any;const payload={proposal_id:r.data.id,corretor_id:broker.id,date:'2026-09-17',value:100,percentage:10};assert.equal((await f.user.from('commission').insert(payload)).error,null);assert.ok((await f.user.from('commission').insert(payload)).error);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM commission').get()?.n,1)});
test('valores inválidos são rejeitados',async()=>{const f=await seed();assert.ok((await f.user.from('property').update({price:-1}).eq('id','pa')).error);assert.ok((await f.user.from('revenue').insert({description:'X',amount:NaN,date:'2026-09-17'})).error)});
test('cadastro é atômico e verificação de email necessária',async()=>{const f=fixture();await createCompany(f.ctx,{name:'Teste A',slug:'teste',ownerEmail:'owner@example.com'},true);await assert.rejects(()=>createCompany(f.ctx,{name:'Teste B',slug:'teste',ownerEmail:'other@example.com'},true));assert.equal(f.db.prepare('SELECT COUNT(*) n FROM company_user').get()?.n,1);f.db.exec('UPDATE users SET email_verified=0');await assert.rejects(()=>createCompany(f.ctx,{name:'Teste C',ownerEmail:'owner@example.com'},true),/Verifique/)});
test('Master é vinculado a email verificado e projeto atual, nunca primeiro visitante',async()=>{const no={sql:async()=>({rows:[]})};const yes={sql:async()=>({rows:[{email:'x@example.com',email_verified:1}]})};for(const env of [{BLINK_PROJECT_ID:'p',OWNER_PROJECT_ID:'p'},{BLINK_PROJECT_ID:'p',OWNER_PROJECT_ID:'other',OWNER_EMAIL:'x@example.com'}])assert.equal(await ownerEligible({userId:'x',email:'x@example.com'},env,no),false);assert.equal(await ownerEligible({userId:'x',email:'x@example.com'},{BLINK_PROJECT_ID:'p',OWNER_PROJECT_ID:'p',OWNER_EMAIL:'x@example.com'},yes),true)});
