/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as MasterRouteImport } from './routes/master'
import { Route as ResetSenhaRouteImport } from './routes/reset-senha'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as AppAiGrowthRouteImport } from './routes/app.ai-growth'
import { Route as AppComissoesRouteImport } from './routes/app.comissoes'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppImoveisRouteImport } from './routes/app.imoveis'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppPlanoRouteImport } from './routes/app.plano'
import { Route as AppPropostasRouteImport } from './routes/app.propostas'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppVisitasRouteImport } from './routes/app.visitas'
import { Route as DemoAiGrowthRouteImport } from './routes/demo.ai-growth'
import { Route as DemoDashboardRouteImport } from './routes/demo.dashboard'
import { Route as DemoFinanceiroRouteImport } from './routes/demo.financeiro'
import { Route as DemoImoveisRouteImport } from './routes/demo.imoveis'
import { Route as DemoLeadsRouteImport } from './routes/demo.leads'
import { Route as DemoPipelineRouteImport } from './routes/demo.pipeline'
import { Route as DemoPropostasRouteImport } from './routes/demo.propostas'
import { Route as DemoRelatoriosRouteImport } from './routes/demo.relatorios'
import { Route as DemoVisitasRouteImport } from './routes/demo.visitas'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'
import { Route as MasterConfiguracoesRouteImport } from './routes/master.configuracoes'
import { Route as MasterListaImobiliariasRouteImport } from './routes/master.lista-imobiliarias'
import { Route as MasterNovaImobiliariaRouteImport } from './routes/master.nova-imobiliaria'
import { Route as MasterPainelRouteImport } from './routes/master.painel'
import { Route as VitrineSlugRouteImport } from './routes/vitrine.$slug'
import { Route as AgendarVisitaSlugIdRouteImport } from './routes/agendar-visita.$slug.$id'
import { Route as ImovelSlugIdRouteImport } from './routes/imovel.$slug.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSenhaRoute = ResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiGrowthRoute = AppAiGrowthRouteImport.update({
  id: '/ai-growth',
  path: '/ai-growth',
  getParentRoute: () => AppRoute,
} as any)
const AppComissoesRoute = AppComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisRoute = AppImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanoRoute = AppPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitasRoute = AppVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => AppRoute,
} as any)
const DemoAiGrowthRoute = DemoAiGrowthRouteImport.update({
  id: '/ai-growth',
  path: '/ai-growth',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFinanceiroRoute = DemoFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DemoRoute,
} as any)
const DemoImoveisRoute = DemoImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => DemoRoute,
} as any)
const DemoLeadsRoute = DemoLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPipelineRoute = DemoPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPropostasRoute = DemoPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRelatoriosRoute = DemoRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => DemoRoute,
} as any)
const DemoVisitasRoute = DemoVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => DemoRoute,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/imoveis/$slug',
  path: '/imoveis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterConfiguracoesRoute = MasterConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterListaImobiliariasRoute = MasterListaImobiliariasRouteImport.update({
  id: '/lista-imobiliarias',
  path: '/lista-imobiliarias',
  getParentRoute: () => MasterRoute,
} as any)
const MasterNovaImobiliariaRoute = MasterNovaImobiliariaRouteImport.update({
  id: '/nova-imobiliaria',
  path: '/nova-imobiliaria',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPainelRoute = MasterPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => MasterRoute,
} as any)
const VitrineSlugRoute = VitrineSlugRouteImport.update({
  id: '/vitrine/$slug',
  path: '/vitrine/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarVisitaSlugIdRoute = AgendarVisitaSlugIdRouteImport.update({
  id: '/agendar-visita/$slug/$id',
  path: '/agendar-visita/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelSlugIdRoute = ImovelSlugIdRouteImport.update({
  id: '/imovel/$slug/$id',
  path: '/imovel/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/ai-growth': typeof AppAiGrowthRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/imoveis': typeof AppImoveisRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/visitas': typeof AppVisitasRoute
  '/demo/ai-growth': typeof DemoAiGrowthRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/imoveis': typeof DemoImoveisRoute
  '/demo/leads': typeof DemoLeadsRoute
  '/demo/pipeline': typeof DemoPipelineRoute
  '/demo/propostas': typeof DemoPropostasRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/demo/visitas': typeof DemoVisitasRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/lista-imobiliarias': typeof MasterListaImobiliariasRoute
  '/master/nova-imobiliaria': typeof MasterNovaImobiliariaRoute
  '/master/painel': typeof MasterPainelRoute
  '/vitrine/$slug': typeof VitrineSlugRoute
  '/agendar-visita/$slug/$id': typeof AgendarVisitaSlugIdRoute
  '/imovel/$slug/$id': typeof ImovelSlugIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/ai-growth': typeof AppAiGrowthRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/imoveis': typeof AppImoveisRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/visitas': typeof AppVisitasRoute
  '/demo/ai-growth': typeof DemoAiGrowthRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/imoveis': typeof DemoImoveisRoute
  '/demo/leads': typeof DemoLeadsRoute
  '/demo/pipeline': typeof DemoPipelineRoute
  '/demo/propostas': typeof DemoPropostasRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/demo/visitas': typeof DemoVisitasRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/lista-imobiliarias': typeof MasterListaImobiliariasRoute
  '/master/nova-imobiliaria': typeof MasterNovaImobiliariaRoute
  '/master/painel': typeof MasterPainelRoute
  '/vitrine/$slug': typeof VitrineSlugRoute
  '/agendar-visita/$slug/$id': typeof AgendarVisitaSlugIdRoute
  '/imovel/$slug/$id': typeof ImovelSlugIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/app/ai-growth': typeof AppAiGrowthRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/imoveis': typeof AppImoveisRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/plano': typeof AppPlanoRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/visitas': typeof AppVisitasRoute
  '/demo/ai-growth': typeof DemoAiGrowthRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/imoveis': typeof DemoImoveisRoute
  '/demo/leads': typeof DemoLeadsRoute
  '/demo/pipeline': typeof DemoPipelineRoute
  '/demo/propostas': typeof DemoPropostasRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/demo/visitas': typeof DemoVisitasRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/lista-imobiliarias': typeof MasterListaImobiliariasRoute
  '/master/nova-imobiliaria': typeof MasterNovaImobiliariaRoute
  '/master/painel': typeof MasterPainelRoute
  '/vitrine/$slug': typeof VitrineSlugRoute
  '/agendar-visita/$slug/$id': typeof AgendarVisitaSlugIdRoute
  '/imovel/$slug/$id': typeof ImovelSlugIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/app/ai-growth'
    | '/app/comissoes'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/imoveis'
    | '/app/leads'
    | '/app/onboarding'
    | '/app/pipeline'
    | '/app/plano'
    | '/app/propostas'
    | '/app/relatorios'
    | '/app/visitas'
    | '/demo/ai-growth'
    | '/demo/dashboard'
    | '/demo/financeiro'
    | '/demo/imoveis'
    | '/demo/leads'
    | '/demo/pipeline'
    | '/demo/propostas'
    | '/demo/relatorios'
    | '/demo/visitas'
    | '/imoveis/$slug'
    | '/master/configuracoes'
    | '/master/lista-imobiliarias'
    | '/master/nova-imobiliaria'
    | '/master/painel'
    | '/vitrine/$slug'
    | '/agendar-visita/$slug/$id'
    | '/imovel/$slug/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/app/ai-growth'
    | '/app/comissoes'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/imoveis'
    | '/app/leads'
    | '/app/onboarding'
    | '/app/pipeline'
    | '/app/plano'
    | '/app/propostas'
    | '/app/relatorios'
    | '/app/visitas'
    | '/demo/ai-growth'
    | '/demo/dashboard'
    | '/demo/financeiro'
    | '/demo/imoveis'
    | '/demo/leads'
    | '/demo/pipeline'
    | '/demo/propostas'
    | '/demo/relatorios'
    | '/demo/visitas'
    | '/imoveis/$slug'
    | '/master/configuracoes'
    | '/master/lista-imobiliarias'
    | '/master/nova-imobiliaria'
    | '/master/painel'
    | '/vitrine/$slug'
    | '/agendar-visita/$slug/$id'
    | '/imovel/$slug/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/app/ai-growth'
    | '/app/comissoes'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/imoveis'
    | '/app/leads'
    | '/app/onboarding'
    | '/app/pipeline'
    | '/app/plano'
    | '/app/propostas'
    | '/app/relatorios'
    | '/app/visitas'
    | '/demo/ai-growth'
    | '/demo/dashboard'
    | '/demo/financeiro'
    | '/demo/imoveis'
    | '/demo/leads'
    | '/demo/pipeline'
    | '/demo/propostas'
    | '/demo/relatorios'
    | '/demo/visitas'
    | '/imoveis/$slug'
    | '/master/configuracoes'
    | '/master/lista-imobiliarias'
    | '/master/nova-imobiliaria'
    | '/master/painel'
    | '/vitrine/$slug'
    | '/agendar-visita/$slug/$id'
    | '/imovel/$slug/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  MasterRoute: typeof MasterRouteWithChildren
  ResetSenhaRoute: typeof ResetSenhaRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  ImoveisSlugRoute: typeof ImoveisSlugRoute
  VitrineSlugRoute: typeof VitrineSlugRoute
  AgendarVisitaSlugIdRoute: typeof AgendarVisitaSlugIdRoute
  ImovelSlugIdRoute: typeof ImovelSlugIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-senha': {
      id: '/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof ResetSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ai-growth': {
      id: '/app/ai-growth'
      path: '/ai-growth'
      fullPath: '/app/ai-growth'
      preLoaderRoute: typeof AppAiGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comissoes': {
      id: '/app/comissoes'
      path: '/comissoes'
      fullPath: '/app/comissoes'
      preLoaderRoute: typeof AppComissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis': {
      id: '/app/imoveis'
      path: '/imoveis'
      fullPath: '/app/imoveis'
      preLoaderRoute: typeof AppImoveisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plano': {
      id: '/app/plano'
      path: '/plano'
      fullPath: '/app/plano'
      preLoaderRoute: typeof AppPlanoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas': {
      id: '/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visitas': {
      id: '/app/visitas'
      path: '/visitas'
      fullPath: '/app/visitas'
      preLoaderRoute: typeof AppVisitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/demo/ai-growth': {
      id: '/demo/ai-growth'
      path: '/ai-growth'
      fullPath: '/demo/ai-growth'
      preLoaderRoute: typeof DemoAiGrowthRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/financeiro': {
      id: '/demo/financeiro'
      path: '/financeiro'
      fullPath: '/demo/financeiro'
      preLoaderRoute: typeof DemoFinanceiroRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/imoveis': {
      id: '/demo/imoveis'
      path: '/imoveis'
      fullPath: '/demo/imoveis'
      preLoaderRoute: typeof DemoImoveisRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/leads': {
      id: '/demo/leads'
      path: '/leads'
      fullPath: '/demo/leads'
      preLoaderRoute: typeof DemoLeadsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/pipeline': {
      id: '/demo/pipeline'
      path: '/pipeline'
      fullPath: '/demo/pipeline'
      preLoaderRoute: typeof DemoPipelineRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/propostas': {
      id: '/demo/propostas'
      path: '/propostas'
      fullPath: '/demo/propostas'
      preLoaderRoute: typeof DemoPropostasRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/relatorios': {
      id: '/demo/relatorios'
      path: '/relatorios'
      fullPath: '/demo/relatorios'
      preLoaderRoute: typeof DemoRelatoriosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/visitas': {
      id: '/demo/visitas'
      path: '/visitas'
      fullPath: '/demo/visitas'
      preLoaderRoute: typeof DemoVisitasRouteImport
      parentRoute: typeof DemoRoute
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/imoveis/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/configuracoes': {
      id: '/master/configuracoes'
      path: '/configuracoes'
      fullPath: '/master/configuracoes'
      preLoaderRoute: typeof MasterConfiguracoesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/lista-imobiliarias': {
      id: '/master/lista-imobiliarias'
      path: '/lista-imobiliarias'
      fullPath: '/master/lista-imobiliarias'
      preLoaderRoute: typeof MasterListaImobiliariasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/nova-imobiliaria': {
      id: '/master/nova-imobiliaria'
      path: '/nova-imobiliaria'
      fullPath: '/master/nova-imobiliaria'
      preLoaderRoute: typeof MasterNovaImobiliariaRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/painel': {
      id: '/master/painel'
      path: '/painel'
      fullPath: '/master/painel'
      preLoaderRoute: typeof MasterPainelRouteImport
      parentRoute: typeof MasterRoute
    }
    '/vitrine/$slug': {
      id: '/vitrine/$slug'
      path: '/vitrine/$slug'
      fullPath: '/vitrine/$slug'
      preLoaderRoute: typeof VitrineSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar-visita/$slug/$id': {
      id: '/agendar-visita/$slug/$id'
      path: '/agendar-visita/$slug/$id'
      fullPath: '/agendar-visita/$slug/$id'
      preLoaderRoute: typeof AgendarVisitaSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$slug/$id': {
      id: '/imovel/$slug/$id'
      path: '/imovel/$slug/$id'
      fullPath: '/imovel/$slug/$id'
      preLoaderRoute: typeof ImovelSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiGrowthRoute: typeof AppAiGrowthRoute
  AppComissoesRoute: typeof AppComissoesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppImoveisRoute: typeof AppImoveisRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPlanoRoute: typeof AppPlanoRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppVisitasRoute: typeof AppVisitasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiGrowthRoute: AppAiGrowthRoute,
  AppComissoesRoute: AppComissoesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppImoveisRoute: AppImoveisRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPlanoRoute: AppPlanoRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppVisitasRoute: AppVisitasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAiGrowthRoute: typeof DemoAiGrowthRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoFinanceiroRoute: typeof DemoFinanceiroRoute
  DemoImoveisRoute: typeof DemoImoveisRoute
  DemoLeadsRoute: typeof DemoLeadsRoute
  DemoPipelineRoute: typeof DemoPipelineRoute
  DemoPropostasRoute: typeof DemoPropostasRoute
  DemoRelatoriosRoute: typeof DemoRelatoriosRoute
  DemoVisitasRoute: typeof DemoVisitasRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAiGrowthRoute: DemoAiGrowthRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoFinanceiroRoute: DemoFinanceiroRoute,
  DemoImoveisRoute: DemoImoveisRoute,
  DemoLeadsRoute: DemoLeadsRoute,
  DemoPipelineRoute: DemoPipelineRoute,
  DemoPropostasRoute: DemoPropostasRoute,
  DemoRelatoriosRoute: DemoRelatoriosRoute,
  DemoVisitasRoute: DemoVisitasRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface MasterRouteChildren {
  MasterConfiguracoesRoute: typeof MasterConfiguracoesRoute
  MasterListaImobiliariasRoute: typeof MasterListaImobiliariasRoute
  MasterNovaImobiliariaRoute: typeof MasterNovaImobiliariaRoute
  MasterPainelRoute: typeof MasterPainelRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterConfiguracoesRoute: MasterConfiguracoesRoute,
  MasterListaImobiliariasRoute: MasterListaImobiliariasRoute,
  MasterNovaImobiliariaRoute: MasterNovaImobiliariaRoute,
  MasterPainelRoute: MasterPainelRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  MasterRoute: MasterRouteWithChildren,
  ResetSenhaRoute: ResetSenhaRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  ImoveisSlugRoute: ImoveisSlugRoute,
  VitrineSlugRoute: VitrineSlugRoute,
  AgendarVisitaSlugIdRoute: AgendarVisitaSlugIdRoute,
  ImovelSlugIdRoute: ImovelSlugIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
